USE meta_tags;

-- INSERT INTO images (image_file_name) VALUES ('P-181-0001.jpg');

-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('1/31/1905', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Alexander von Humboldt', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Berlin', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Bibliothek', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Dominic Colnaghi', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('England', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Germany', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Hildebrandt', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('library', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('London', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Paul Colnaghi', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Portrait', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Storch & Kramer', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Art', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Building', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Collection', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Holy places', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Illustration', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('columns', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('human figures', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('interiors', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('stairs', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('19th century', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('books', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('bookshelf', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('bookshelves', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('boxes', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('bust', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('busts', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('carpet', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('chair', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('color', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('door', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('dooway', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('drawing', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('explorer', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('geography', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('German', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('globe', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('home', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('house', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('ladder', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('man', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('maps', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('office', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('painting', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('paintings', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('reading', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('room', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('rug', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('scientist', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('scrolls', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('study', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Study Room', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('table', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('taxidermy', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('telescope', 0, 0, 1);
-- INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('von Humboldt', 0, 0, 1);

INSERT INTO images (image_file_name) VALUES ('APHP_S11_F1_6.jpg');

INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('1930', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Adler Planetarium', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Chicago', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('opening day', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('outside', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('visitors ', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('bodies of water', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('castles', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('men', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('ships', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('towers', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('1900s', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('1930s', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('admission', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('assembly', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('automobiles', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Black and white', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('brutalist architecture', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('buick', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('building', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('bumper to bumper', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('busy', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('cab', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('cabs', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('car park', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('cars', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('classic cars', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('concrete', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('crowd', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('daylight', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('entrance', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('entrance queues', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('entry', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('event', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('exhibit', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('exterior', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Fellow cab', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('funeral', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('gathering of people', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('grass', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('group', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('hats', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('historic', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('history', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('line', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('monochrome', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('outdoors', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('parked cars', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('parking', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('people', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('planetarium building', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('public building', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('queue', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('road', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('ropes', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('running boards', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('standing in line ', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('stone building', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('street', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('summer', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('taxi', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('taxi stand', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('tickets', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('tires', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('Tourist attraction', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('transportation', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('waiting line', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('women', 0, 0, 2);
INSERT INTO tags (tag, accepted, rejected, image_id) VALUES ('yellow cab', 0, 0, 2);